apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-834l
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-834l@sha256:58b9503dcd7cd0ee740b6a0eef007647bcdf8099e3f04b7ab763c581918a7702
        name: my-nodejs
        resources: {}
status: {}
